name: svm
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.3.5
  - pip=21.3.1
  - scikit-learn=1.0.2
  - matplotlib=3.2.2
  - pillow=8.4.0
  - pip:
      - wandb==0.12.10
      - imbalanced-learn==0.9.0
      - mlxtend==0.19.0
      - mlflow==1.14.1
      - omegaconf==2.1.1