main:
  project_name: bank_change_name
  experiment_name: dev
  execute_steps:
    - download
    - preprocess
    - check_data
    - segregate
    - svm
    - evaluate
  # This seed will be used to seed the random number generator
  # to ensure repeatibility of the data splits and other
  # pseudo-random operations
  random_seed: 42
data:
  file_url: "https://docs.google.com/uc?export=download&id=1AtKo0u4r251RvZYkUAFtGoA3UAw3AbhH"
  reference_dataset: "raw_data.csv:latest"
  # Threshold for Kolomorov-Smirnov test
  ks_alpha: 0.05
  test_size: 0.3
  val_size: 0.3
  # Stratify according to the target when splitting the data
  # in train/test or in train/val
  stratify: "y"
svm_pipeline:
  svm:
    kernel: "linear"
    gamma: "scale"
  numerical_pipe:
    model: 0
  export_artifact: "model_export"